const PDFDocument = require('pdfkit');

const { getVillageById } = require('./villageService.js');

const { getVillageMetrics } = require('./satelliteService.js');

const { getVillageScore } = require('./scoreService.js');

const { getCurrentWeather } = require('./weatherService.js');

const {
  generateVillageRecommendations
} = require('./cropRecommendationService.js');


 async function generateVillageReportPDF(villageId, year = 2024, res) {
  const village = getVillageById(villageId) || { name: 'Mulshi', district: 'Pune', state: 'Maharashtra', coordinates: [18.52, 73.53] };
  const metrics = await getVillageMetrics(villageId, year);
  const score = await getVillageScore(villageId, year);
  const weather = await getCurrentWeather(village.coordinates[0], village.coordinates[1]);
  const recs = await generateVillageRecommendations(village, metrics, score);

  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="GramDrishti_Report_${village.name}_${year}.pdf"`);

  doc.pipe(res);

  // Header Title
  doc.fontSize(22).fillColor('#1b4332').text('GramDrishti Farmer Advisory & Weather Report', { align: 'center' });
  doc.fontSize(12).fillColor('#555555').text(`Village: ${village.name} | District: ${village.district}, ${village.state} | Year: ${year}`, { align: 'center' });
  doc.moveDown(1.5);

  // Health Score Section
  doc.fontSize(16).fillColor('#2d6a4f').text('1. Executive Agricultural & Ecological Summary');
  doc.moveDown(0.5);
  doc.fontSize(12).fillColor('#000000')
     .text(`- Agricultural Health Score: ${score.overallScore} / 100 (${score.status})`)
     .text(`- Primary Soil Type: ${village.soilType || 'Black Cotton Soil'}`)
     .text(`- Current Weather: ${weather.temp_c}°C, ${weather.condition}, Humidity: ${weather.humidity_pct}%`)
     .text(`- Soil Moisture Level: ${metrics.soil_moisture} | Vegetation Canopy (NDVI): ${metrics.ndvi}`);
  doc.moveDown(1.5);

  // Crop Recommendations Section
  doc.fontSize(16).fillColor('#2d6a4f').text('2. Localized Crop Recommendations');
  doc.moveDown(0.5);

  recs.forEach((rec, idx) => {
    doc.fontSize(13).fillColor('#1b4332').text(`${idx + 1}. ${rec.cropName} (Suitability Match: ${rec.suitabilityScore}%)`);
    doc.fontSize(10).fillColor('#333333')
       .text(`   • Sowing Window: ${rec.sowingWindow}`)
       .text(`   • Expected Yield: ${rec.expectedYield}`)
       .text(`   • Soil Compatibility: ${rec.soilMatch}`)
       .text(`   • Irrigation & Water Need: ${rec.waterNeed}`)
       .text(`   • Key Advisory: ${rec.description}`)
       .moveDown(0.5);
  });

  doc.moveDown(1.5);
  doc.fontSize(10).fillColor('#888888').text('Generated by GramDrishti Platform (AG-02 MERN Architecture).', { align: 'center' });

  doc.end();
}


module.exports = generateVillageReportPDF;